<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Timing extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Timing_model');

        $this->load->library('session');
		$this->school_id = $this->session->userdata('school_id');
    } 

    /*
     * Listing of timing
     */
    function index()
    {
        $data['timing'] = $this->Timing_model->get_all_timing();
        $this->load->model('Edu_class_model');
        $data['all_class'] = $this->Edu_class_model->get_all_class();

        $this->load->template('timing/index',$data);
    }

    /*
     * Adding or Editing a timing
     */
    function addedit($mode = 'add', $ID = 0) {

        $this->load->library('form_validation');

        $this->form_validation->set_rules('IN_OUT','IN/OUT','required');
		$this->form_validation->set_rules('Cut_Off_Time','Cut Off Time','required');
		$this->form_validation->set_rules('GressTime_To_InOut','Gress Time To In/Out','required');
		$this->form_validation->set_rules('Class_ID','Class ID','required');
		$this->form_validation->set_rules('School_ID','School ID','required');

        $params = array(
                'IN_OUT' => $this->input->post('IN_OUT'),
                'Cut_Off_Time' => str_replace(" ", "", $this->input->post('Cut_Off_Time')),
                'GressTime_To_InOut' => str_replace(" ", "", $this->input->post('GressTime_To_InOut')),
                'Class_ID' => $this->input->post('Class_ID'),
                'School_ID' => $this->input->post('School_ID'),
                'Added_On' => $this->input->post('Added_On'),
                'Updated_On' => $this->input->post('Updated_On'),
                'Updated_By' => $this->input->post('Updated_By'),
                'Is_Deleted' => $this->input->post('Is_Deleted'),
            );

        if($this->form_validation->run())     
        {
            if ($mode == 'add') {
                $result = $timing_id = $this->Timing_model->add_timing($params);  
                
                if ($result) {
                    $this->session->set_flashdata('flashInfo', 'Timing added sucessfully.');
                } else {
                    $this->session->set_flashdata('flashError', 'Failed to add Timing!');
                }
                
            } else if ($mode == 'edit') {
                $result = $this->Timing_model->update_timing($ID,$params); 
                
                if ($result) {
                    $this->session->set_flashdata('flashInfo', 'Timing modified sucessfully.');
                } else {
                    $this->session->set_flashdata('flashError', 'Failed to modify Timing!');
                }
            }

            redirect('timing/index');

        } else {   

            // check if the timing exists before trying to edit it
            $data['timing'] = $this->Timing_model->get_timing($ID);
   
            $this->load->model('Edu_class_model');
            $data['all_class'] = $this->Edu_class_model->get_all_class();
    
            if (empty($data['timing']) && $mode == 'edit') {
                $this->session->set_flashdata('flashError', 'The poc you are trying to edit does not exist.');
                redirect('timing/index');
            } else if ($mode == 'add') {
                $data['timing'] = $params;
            }

            $this->load->template('timing/addedit', $data);
        }

    }

    /*
     * Deleting timing
     */
    function remove($ID)
    {
        $timing = $this->Timing_model->get_timing($ID);

        // check if the timing exists before trying to delete it
        if(isset($timing['ID']))
        {
            $this->Timing_model->delete_timing($ID);
            $this->session->set_flashdata('flashInfo','The timing deleted successfully.');           
        } else {
            $this->session->set_flashdata('flashError','The timing you are trying to delete does not exist.');
        }    
        
        redirect('timing/index');
    }
    
}
