<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Candidate_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get candidate_type by ID
     */
    function get_candidate_type($ID)
    {
        return $this->db->get_where('candidate_type',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all candidate_type
     */
    function get_all_candidate_type()
    {
        return $this->db->get('candidate_type')->result_array();
    }
    
    /*
     * function to add new candidate_type
     */
    function add_candidate_type($params)
    {
        $this->db->insert('candidate_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update candidate_type
     */
    function update_candidate_type($ID,$params)
    {
        $this->db->where('ID',$ID);
        $this->db->update('candidate_type',$params);
    }
    
    /*
     * function to delete candidate_type
     */
    function delete_candidate_type($ID)
    {
        $this->db->delete('candidate_type',array('ID'=>$ID));
    }
}
