<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Class_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get class by ID
     */
    function get_class($ID)
    {
        return $this->db->get_where('class',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all class
     */
    function get_all_class()
    {
        return $this->db->get('class')->result_array();
    }
    
    /*
     * function to add new class
     */
    function add_class($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update class
     */
    function update_class($ID,$params)
    {
        $this->db->where('ID',$ID);
        $this->db->update('class',$params);
    }
    
    /*
     * function to delete class
     */
    function delete_class($ID)
    {
        $this->db->delete('class',array('ID'=>$ID));
    }
}
