<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Class_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get class by ID
     */
    function get_class($ID)
    {
        return $this->db->get_where('class',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all class
     */
    function get_all_class($params = array())
    {
        return $this->db->get_where('class', $params)->result_array();
    }

    /*
    * Get all class by school
    */
    function get_all_class_by_school($School_ID) {
        
        $candidate = $School_ID.'_candidate';

        $this->db->select('cl.Name, cl.Section');
        $this->db->from('class cl');
        $this->db->join($candidate . ' as cd', 'cl.ID = cd.Class_ID');
        $this->db->where('cd.School_ID', $School_ID);

        $result = $this->db->get()->result_array();
        return $result;
    }

    /*
     * function to add new class
     */
    function add_class($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update class
     */
    function update_class($ID,$params)
    {
        $this->db->where('ID',$ID);
        $this->db->update('class',$params);
    }
    
    /*
     * function to delete class
     */
    function delete_class($ID)
    {
        $this->db->delete('class',array('ID'=>$ID));
    }
}
