<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Customer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		$this->load->database();
    }
    
    /*
     * Get customer by customerNumber
     */
    function get_customer($customerNumber)
    {
        return $this->db->get_where('customers',array('customerNumber'=>$customerNumber))->row_array();
    }
    
    /*
     * Get all customers
     */
    function get_all_customers()
    {
        return $this->db->get('customers')->result_array();
    }
    
    /*
     * function to add new customer
     */
    function add_customer($params)
    {
        $this->db->insert('customers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer
     */
    function update_customer($customerNumber,$params)
    {
        $this->db->where('customerNumber',$customerNumber);
        $this->db->update('customers',$params);
    }
    
    /*
     * function to delete customer
     */
    function delete_customer($customerNumber)
    {
        $this->db->delete('customers',array('customerNumber'=>$customerNumber));
    }
}
