<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Edu_class_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get educlass by ID
     */
    function get_educlass($ID)
    {
        return $this->db->get_where('class',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all educlasses
     */
    function get_all_educlasses()
    {
        return $this->db->get('class')->result_array();
    }
    
    /*
     * function to add new educlass
     */
    function add_educlass($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update educlass
     */
    function update_educlass($ID,$params)
    {
        $this->db->where('ID',$ID);
        $this->db->update('class',$params);
    }
    
    /*
     * function to delete educlass
     */
    function delete_educlass($ID)
    {
        $this->db->delete('class',array('ID'=>$ID));
    }
}
