<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Machine_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->school_id = $this->session->userdata('school_id');
    }
    
    /*
     * Get machine by ID
     */
    function get_machine($ID)
    {
        return $this->db->get_where('School_Machines',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all machines
     */
    function get_all_machines()
    {
        $this->db->where('School_ID', $this->school_id);
        return $this->db->get('School_Machines')->result_array();
    }
    
    /*
     * function to add new machine
     */
    function add_machine($params)
    {
        $this->db->insert('School_Machines',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update machine
     */
    function update_machine($ID,$params)
    {
        $this->db->where('ID',$ID);
        $response = $this->db->update('School_Machines',$params);
        if($response)
        {
            return "machine updated successfully";
        }
        else
        {
            return "Error occuring while updating machine";
        }
    }
    
    /*
     * function to delete machine
     */
    function delete_machine($ID)
    {
        $response = $this->db->delete('School_Machines',array('ID'=>$ID));
        if($response)
        {
            return "machine deleted successfully";
        }
        else
        {
            return "Error occuring while deleting machine";
        }
    }
}
