<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class School_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }
    
    /*
     * Get school by ID
     */
    function get_school($ID)
    {
        return $this->db->get_where('school',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all school
     */
    function get_all_school()
    {
        return $this->db->get('school')->result_array();
    }
    
    /*
     * function to add new school
     */
    function add_school($params)
    {
        $this->db->select_max('School_ID');
        $result = $this->db->get('school')->row();  
        $school_id = intval($result->School_ID);

        $params['School_ID'] = ++$school_id;
        $params['ID'] = "SC" . str_pad($school_id, 5, '0', STR_PAD_LEFT);

        $this->db->insert('school', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update school
     */
    function update_school($ID,$params)
    {
        $this->db->where('ID',$ID);
        $this->db->update('school',$params);
    }
    
    /*
     * function to delete school
     */
    function delete_school($ID)
    {
        $this->db->delete('school',array('ID'=>$ID));
    }
}
