<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Sms_provider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sms_provider by ID
     */
    function get_sms_provider($ID)
    {
        return $this->db->get_where('sms_provider',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all sms_provider
     */
    function get_all_sms_provider($params = array())
    {        
        $result = $this->db->get_where('sms_provider', $params)->result_array();        
        return $result;
    }
    
    /*
     * function to add new sms_provider
     */
    function add_sms_provider($params)
    {
        $this->db->insert('sms_provider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sms_provider
     */
    function update_sms_provider($ID,$params)
    {
        $this->db->where('ID',$ID);
        $response = $this->db->update('sms_provider',$params);
        if($response)
        {
            return "sms_provider updated successfully";
        }
        else
        {
            return "Error occuring while updating sms_provider";
        }
    }
    
    /*
     * function to delete sms_provider
     */
    function delete_sms_provider($ID)
    {
        $response = $this->db->delete('sms_provider',array('ID'=>$ID));
        if($response)
        {
            return "sms_provider deleted successfully";
        }
        else
        {
            return "Error occuring while deleting sms_provider";
        }
    }
}
